### PR TITLE
add Tutorial 1016 - Brushes II (en)

### PR DESCRIPTION
**Pull request by showrav-ansary**

### CODE REVIEW

**Comment by showrav-ansary** [comment]
@rebornplusplus vaia I am confused about the coordinates of the x-axes given for each dust point. I am getting the catch there if there is any.

**Review by rebornplusplus — CHANGES_REQUESTED** [review]
Great work! Indent your code properly and will merge afterwards.

**Comment by rebornplusplus** [comment]
There's no catch about the x co-ordinates.

**Comment by showrav-ansary** [comment]
@rebornplusplus Thank you for the clarification vaia 💟

**Review by rebornplusplus — APPROVED** [review]

**Comment by rebornplusplus** [comment]
Thank you for your contribution!

**Pull request merged**
