### PR TITLE
Added tutorial LOJ 1294 - Positive Negative Sign (en)

### PR DESCRIPTION
**Pull request by showrav-ansary**

### CODE REVIEW

**Comment by showrav-ansary** [comment]
Hi. I need help summarizing the problem statement as it is vital for this solution and also the description itself is really short. I felt summarizing can be left out for this particular problem.

**Comment by rebornplusplus** [comment]
Remove the _Summary, Input, Output_ sections altogether.

**Comment by showrav-ansary** [comment]
Thank you for the feed back. done!

**Comment by rebornplusplus** [comment]
Merged. Thank you for your contribution. :)

**Pull request merged**
