### PR TITLE
add LOJ 1013 - Love Calculator (en)

### PR DESCRIPTION
**Pull request by showrav-ansary**

### CODE REVIEW

**Review by rebornplusplus — CHANGES_REQUESTED** [review]
Hello. Great efforts!

However, I feel like you missed to clearly state the dp transitions. You have elaborated on **how** you are calculating but for dp solutions, it's better to show the base cases and transitions first i.e. **why** you want to do **what**.

For example, let `dp(i, j)` be the length of the shortest string in which `p[i..], q[j..]` strings appear as sub-sequences. We may write,
```
dp( len(p), j ) = len(q) - j
dp( i, len(q) ) = len(p) - i

dp( i, j ) = min( 1 + dp( i + 1, j ), 1 + dp( i, j + 1) )             if p[i] != q[j]
             dp( i + 1, j + 1 ) + 1                                   else
```
Now, if you explain the base cases and how you ended up with the transitions, it's easier to follow for anybody.

Bonus: Some tips I found helpful over the years:
* It's a better idea to not go near rigorous implementation details unless it is absolutely necessary.
* Too many bold stuffs in an article is very disturbing and often unnecessary.
* It's easy to follow some steps if they are written in (un)ordered lists rather than in a paragraph.
* Writing a portion of related sentences in a paragraph provides better readability than a bunch of separated lines.

**Comment by showrav-ansary** [comment]
@rebornplusplus Extremely sorry for the delay. I had a rough month. Finals projects internships uggghh. Thank you for the guidelines. Let me have some time. My exam ends at 28th March, hopefully will do the changes. Sorry and thank you again vaia ❤️

**Comment by showrav-ansary** [comment]
@rebornplusplus I have included the transitions and all the cases to consider. Vaia the base case has been mentioned in the recursive code solution. I have linked the resources that explains the 1st unnecessary paragraph of strings, substrings and subsequence but I think it may help the new comers/college kids quickly; still, should I edit those too?

**Review by rebornplusplus — APPROVED** [review]
Good work. :clap:

**Pull request merged**
