### PR TITLE
Add tutorial for LOJ-1192 Left Right

### PR DESCRIPTION
**Pull request by nfpranta**
Link : http://lightoj.com/volume_showproblem.php?problem=1192

### CODE REVIEW

**Comment by Tahanima** [comment]
Hi @nfpranta,
Some of the issues in your other pull request persist here as well. So, please fix those. Also, can you provide images in your explanation? It is very difficult to visualize/understand the solution just by reading the contents.

**Comment by nfpranta** [comment]
[1192.pdf](https://github.com/lightoj-dev/problem-tutorials/files/5738196/1192.pdf)

**Comment by nfpranta** [comment]
Hello @Tahanima apu,I don't know how to attach this pdf with the main file. :')

**Comment by Tahanima** [comment]
Hi @nfpranta,
Why do you need to attach a PDF file?

Can you please tidy up your writing a bit? There are a lot of grammatical errors. Also, please remove the bold styling for texts under the `Resources:` section.

**Comment by nfpranta** [comment]
Hello, @Tahanima apu,
I couldn't find a way to upload the png files over a single pull request. If there is any way to merge these together,it would be of great help. I searched for videos on Youtube but couldn't find any good resource there. But if there is any kind of difficulty , it would of great help if you please provide me any link from where I can learn to fulfill what I am asked to.

**Pull request closed without merging**
