### PR TITLE
Added Tutorial for Dimik Even Odd 1 

### PR DESCRIPTION
**Pull request by walleeva2018**

### CODE REVIEW

**Comment by walleeva2018** [comment]
Hello Sir , I have created a several folder for DIMIK problems . As there is no LOJ id for these problems so i only added the name . Is it okay ? if so i will create PRs for rest of them

**Comment by rebornplusplus** [comment]
This PR isn’t gonna work, since there are multiple tutorials proposed in this. #411 was alright.

Also, regarding the Dimik/<problem>, do add the links here of the problems. I am not sure where these problem descriptions are located on LightOJ.

**Comment by walleeva2018** [comment]
Sir I have created this PR from separate branch not same with #411 . Also it contains only 1 file others are deleted .Please tell me how can i create PR of several problems at the same time as others are in review.

**Comment by rebornplusplus** [comment]
It does contain a lot of files though. Check the "Files Changed" tab.
image

**Comment by walleeva2018** [comment]
Oh my bad. Sorry . Let me fix this !!

**Pull request closed without merging**
