### PR TITLE
Add: English editorial for LightOj 1054 - Efficient Pseudo Code

### PR DESCRIPTION
**Pull request by Yankee-16**
Added English tutorial for LightOj 1054 - Efficient Pseudo Code. Let me know if anything is wrong

### CODE REVIEW

**Comment by rebornplusplus** [comment]
Can you indent your code with either only tabs or spaces? Also, please replace "LightOj" with "LightOJ" and you can also remove the "Problem Statement" link at the very beginning since that seems redundant. Thank you.

**Comment by Yankee-16** [comment]
Sure, I'll update it soon.

**Comment by Yankee-16** [comment]
I've updated the editorial. Please check it and let me know if any changes are needed.

**Comment by rebornplusplus** [comment]
Hello. Should have mentioned this before, but can you kindly place the image file you included, in the `1054` folder and instead of an external link, link to the local file?

Also, indenting is still messed up. You can replace all `\t` with 4 spaces I think.
image

**Comment by Yankee-16** [comment]
Ok, I'll update it ASAP

**Comment by Yankee-16** [comment]
I've updated the files. Please check if it is ok now

**Comment by nfpranta** [comment]
Hello @Yankee-16 ..Nice work. But can you please explain the reason why you wrote the now<0 condition? The thing is I just solved this problem and I faced quite a lot of issues with finding the reason why it was going wrong without the now<0 condition. Other than that reasoning seems ok. Also please add some editorials/videos on inverse mod and Fermat's Little Theorem for those who have no knowledge regarding this stuff.It's very tiring for people to look at something and glance for the whole day without being able to figure out why this works.Thank You

**Comment by Yankee-16** [comment]
Sure. I also wanted to add tutorial for Inverse mod, but couldn’t find any suitable tutorial. I'll update the editorial soon.

**Comment by rebornplusplus** [comment]
@Yankee-16 let me know when your editorial is updated finally. Everything looks good.

**Comment by Yankee-16** [comment]
@nfpranta @rebornplusplus  I've updated the editorial. Please check it now.

**Comment by rebornplusplus** [comment]
Merged. @Yankee-16, thank you very much for the write-up. 🍬🍬🍬

**Comment by Yankee-16** [comment]
My pleasure 😊

**Pull request merged**
