### PR TITLE
Add English Tutorial for LOJ-1080 Binary simulation

### PR DESCRIPTION
**Pull request by ar-pavel**
#67

### CODE REVIEW

**Comment by rebornplusplus** [comment]
Hello, great effort! :1st_place_medal: 

I have some confusions in some of the parts. Let's discuss them.

 >Fact: as the input string is consist of only 0 and 1, and the type of update is only inverting the index, no matter how many inversions you make it will be same in each odd inversion count and vise versa, 1 will remain 1 after 1,3,5,.. inversions and will become 0 after 2,4,6,.. inversions, for example.

* Shouldn't this be "1 will remain 1 after 2,4, 6.. inversions and will be 0 otherwise"?

* In the image for `query(I, 5, 5)`, shouldn't the node value for `2-4` be 0 instead of 1 since the update is only to the right subtree of `1-7`?

* You mentioned lazy propagation for `invertRange`, but I don't see any propagation in your code. Rather, you are calculating the sum of the values of ancestor nodes for a particular point modulo 2.

**Comment by ar-pavel** [comment]
- Shouldn't this be "1 will remain 1 after 2,4, 6.. inversions and will be 0 otherwise"?
reply:  Yes, you are right. 

- In the image for query(I, 5, 5), shouldn't the node value for 2-4 be 0 instead of 1 since the update is only to the right subtree of 1-7?
reply: those images got messed up with layers while exporting in iPad and my bad, I asked someone else to revise it as I was in a rush for my midterm exam.  

- You mentioned lazy propagation for invertRange, but I don't see any propagation in your code. Rather, you are calculating the sum of the values of ancestor nodes for a particular point modulo 2.

reply: In each invert range query, we are not updating the range instantly, rather we are keeping it in the waiting queue as long as we don't need any of its predecessors to make any operations and this logic comes from lazy propagation. 

I will make another commit after fixing issues 1 and 2 and thanks for figuring it out.

**Comment by ar-pavel** [comment]
@rebornplusplus I made an updated commit.

**Comment by rebornplusplus** [comment]
Your code gets WA I am afraid.

```cpp
printf("%d\n", (query(1,1,len,x) ));
```
Ln 160, You're not calculating the summation modulo 2.

```cpp
if(tl==l and tr==r){
```
Also, at Ln 89, shouldn't this be the following?
```cpp
if(tl>=l and tr<=r){
```

**Comment by ar-pavel** [comment]
Yeah, I should've calculated the modulo 2 value. 
rest others will remain the same.

**Review by rebornplusplus — COMMENTED** [review]
Resolves #67.

**Comment by rebornplusplus** [comment]
Merged.
Thank you for your contribution. Good work. :clap:

**Pull request merged**
