### PR TITLE
Tutorial for LOJ 1133 - Array-Simulation (en and bn)

### PR DESCRIPTION
**Pull request by subhashiscse**

### CODE REVIEW

**Review by rebornplusplus — CHANGES_REQUESTED** [review]
Hello. I see you are a first time contributor.
* Please create an issue with the problem number before you start writing tutorial. Reduces conflicts of interest.
* In a single Pull Request, write a single tutorial. (For example, here, either 1133 or 1425)

That being said, I see you have written tutorial for 1133 and 1425 here. I have reviewed both.
* 1133 is okay. Good work.
* 1425 lacks the most important part, the tutorial. You have only summarized the problem statement and added code, but haven't provided a solution. You may write the solution to 1425 or remove 1425 altogether.

**Comment by subhashiscse** [comment]
Also check it please @rebornplusplus

**Comment by rebornplusplus** [comment]
Um, you haven't changed anything in 1425. Please see the review I left.

**Comment by rebornplusplus** [comment]
Oh I see you have added another PR for 1425. In that case, erase the `1425/` directory from this branch and push.
Also, mention the problem no and name in the PR name. :)

**Comment by subhashiscse** [comment]
Updated :) @rebornplusplus

**Review by rebornplusplus — APPROVED** [review]

**Comment by rebornplusplus** [comment]
Merged. Thank you. :green_apple:

**Pull request merged**
