### PR TITLE
Add English Tutorial for LOJ-1102 Problem Makes Problem

### PR DESCRIPTION
**Pull request by nfpranta**

### CODE REVIEW

**Comment by nfpranta** [comment]
Problem: http://lightoj.com/volume_showproblem.php?problem=1102

**Comment by rebornplusplus** [comment]
Hello @nfpranta. Good work. :+1:  However, please go through the following instructions.

> Each problem will have its own folder with the name of its problem id, such as 1000, 1214. Each folder will contain tutorial as `en.md` file for English and `bn.md` for Bangla language.

Shortly, rename your `1102` file to `en.md` and move it within a folder named `1102`. So the structure should be like this:
```
- 1102/
    + en.md
```

Provide the formula in the description too (before the code); which I think is `(n + k - 1) Choose (k - 1)`?

Your markdown is a little messed up, specially with the _backtick character_. You can preview it [here](https://dillinger.io/). Do your best and I'll take care of the rest.

**Comment by nfpranta** [comment]
I hope everything is ok now but if there is any amendments I can do please tell them as this is the very first time I am trying to contribute to a foreign project..So there might be stuff I might not be familiar with. Your advice will be duly noted.

**Comment by rebornplusplus** [comment]
Hello, I am going through your markdown. But the name should be `en.md` in folder `1102`. You can revert the last commit. The whole fuss about `- 1102/ + en.md` was just a way to visualize the file tree. You can discard that.

**Comment by nfpranta** [comment]
The operators have been discarded...Any further improvement, I can instill here?

**Review by rebornplusplus — APPROVED** [review]
Looks okay. Will fix some spacing myself.

**Comment by rebornplusplus** [comment]
Merged.

Thank you for you contribution @nfpranta! Have an :apple:.

**Pull request merged**
