### PR TITLE
Adding a tutorial for Dimik-Even Odd 2

### PR DESCRIPTION
**Pull request by nfpranta**
Problem Link: https://lightoj.com/problem/dimik-even-odd-2

### CODE REVIEW

**Comment by rebornplusplus** [comment]
Per #414, let's put a hold on to DimikOJ tutorials.

**Comment by faiyaz26** [comment]
> Per #414, let's put a hold on to DimikOJ tutorials.

I have implemented the tutorial sync for the the dimikoj problems. Updated the readme: https://github.com/lightoj-dev/problem-tutorials/blob/main/README.md

You need to follow the directory structure like this: https://github.com/lightoj-dev/problem-tutorials/tree/main/dimik-even-odd-1

**Comment by nfpranta** [comment]
@faiyaz26 bhai,is it according to the updated readme now?

**Comment by nfpranta** [comment]
Hello @rebornplusplus ,can you please check this piece of work here?

**Pull request closed without merging**
