### PR TITLE
1142 - Summing Up Powers (II)

### PR DESCRIPTION
**Pull request by iamsaquib2508**

### CODE REVIEW

**Comment by faiyaz26** [comment]
Please remove the files `.ds_store`
do not add any space on the image file names.

Also add some resources about matrix expo for the solvers, so that people can learn about the algorithm.

**Comment by faiyaz26** [comment]
Please remove the files `.ds_store`
do not add any space on the image file names.

Also add some resource links about matrix expo for the solvers, so that people can learn about the algorithm.

**Comment by iamsaquib2508** [comment]
Not removing the .DS_Store files was my mistake. I intended to do so initially but somehow forgot about it. Sorry for that.

I will update the image names. Noted.

Technically, there is no "matrix exponentiation" present here. I mean, it doesn't involve converting linear recurrence relations into a matrix and using it to solve them or etc. It (current tutorial) just uses Modular Exponentiation on matrix, not the same as Matrix Exponentiation. In terms of the problem description, if 'A' were an integer instead of a matrix, the problem solution and description would be exactly the same, except the O(n^3) extra complexity for multiplication. So I didn't consider them necessary or relevant here (unless you want to make readers explore other related topics). Looking forward to your opinion on this one.

**Comment by faiyaz26** [comment]
@iamsaquib2508 Ah ok. Please remove the redundant files and fix the image names then. Then we will merge it. Thanks.

**Pull request merged**
