### PR TITLE
Tutorial for LOJ 1258 - Making Huge Palindromes

### PR DESCRIPTION
**Pull request by fifo36**

### CODE REVIEW

**Comment by rebornplusplus** [comment]
> Each problem will have its own folder with the name of its problem id, such as 1000, 1214. Each folder will contain tutorial as en.md file for English and bn.md for Bangla language.

Please follow the contribution guideline.

**Comment by fifo36** [comment]
> > Each problem will have its own folder with the name of its problem id, such as 1000, 1214. Each folder will contain tutorial as en.md file for English and bn.md for Bangla language.
> 
> Please follow the contribution guideline.

Is it ok now?

**Comment by faiyaz26** [comment]
Check the rendered output of the file. You need to write it in markdown. Here is the rendered view: https://github.com/lightoj-dev/problem-tutorials/blob/a87c51f9c1fdefd1effe7e469b64e96fc275f119/1258/en.md

The file is not properly rendered. Please take a look at this file for reference: https://github.com/lightoj-dev/problem-tutorials/blob/main/1040/en.md

if you go to the above link and click on the button `raw` you should be able to see the markdown structure.

**Comment by fifo36** [comment]
> Check the rendered output of the file. You need to write it in markdown. Here is the rendered view: https://github.com/lightoj-dev/problem-tutorials/blob/a87c51f9c1fdefd1effe7e469b64e96fc275f119/1258/en.md
> 
> The file is not properly rendered. Please take a look at this file for reference: https://github.com/lightoj-dev/problem-tutorials/blob/main/1040/en.md
> 
> if you go to the above link and click on the button `raw` you should be able to see the markdown structure.
> 
> Also if you don't have enough idea about markdown, learn it from here: https://guides.github.com/features/mastering-markdown/
> 
> You can try using this tool https://dillinger.io/ to get real time preview of a markdown file.

Dear Brother,
I have updated the tutorial. Please let me know if it's ok.

**Comment by rebornplusplus** [comment]
Yes.
Thank you for your contribution.

**Pull request merged**
