### PR TITLE
Added Editorial for LOJ-1283-Shelving Books

### PR DESCRIPTION
**Pull request by Mahmudul-Kabir**

### CODE REVIEW

**Comment by rebornplusplus** [comment]
Hello. Thank you for the PR. But can you please discuss a little bit more about the states and transitions before moving on to implementations?

**Comment by Mahmudul-Kabir** [comment]
On it.

**Comment by rebornplusplus** [comment]
Any updates on this @MahediKamal ?

**Comment by rebornplusplus** [comment]
Any updates @Mahmudul-Kabir ?

**Comment by rebornplusplus** [comment]
I am merging the PR as of now. If you or anyone wants to further work on this, simply create another PR.

**Comment by rebornplusplus** [comment]
Thank you for your contribution.

**Pull request merged**
