### PR TITLE
Added tutorial for LOJ-1112: Curious Robin Hood

### PR DESCRIPTION
**Pull request by sakib3201**
Added the tutorial in English with accepted solution code in C++.

### CODE REVIEW

**Review by rebornplusplus — COMMENTED** [review]
Good tutorial. But you can improve it by adding the naive solution first i.e. explain the queries using an array, then adding the line that "using a BIT or Seg Tree would improve time".

Let me know what you think.

**Comment by faiyaz26** [comment]
@sakib3201 any update on this?

**Comment by sakib3201** [comment]
@faiyaz26 the required changes were added into the last commit. If there is no typos then the branch is ready to be merged

**Review by rebornplusplus — APPROVED** [review]
Looks good. :fountain:

**Comment by rebornplusplus** [comment]
Thanks for your contribution!

**Pull request merged**
