### PR TITLE
Added tutorial of LOJ 1211(en), 1216(en)

### PR DESCRIPTION
**Pull request by showrav-ansary**

### CODE REVIEW

**Comment by showrav-ansary** [comment]
add tutorial for LOJ 1216 - Juice in the Glass (en)

**Comment by rebornplusplus** [comment]
Hello. PR is merged. Thank you for your contribution.

But for future reference, please make separate PRs for individual problems.

**Comment by rebornplusplus** [comment]
Hello. PR is merged. Thank you for your contribution.

But for future reference, please make separate PRs for individual problems. And you need not insert the full problem description, insert only a summary if you can.

**Comment by rebornplusplus** [comment]
Note: the revert commit was an accidental click. Ignore it.

**Pull request merged**
