### PR TITLE
Add tutorial of LOJ 1235 - Coin Change (IV)

### PR DESCRIPTION
**Pull request by MahediKamal**

### CODE REVIEW

**Comment by rebornplusplus** [comment]
Hello. Great work.

Consider the following:

> For improving our solution, let's see what is happening -
        lets we have two coins a,b. We are pushing each element two times.
        So , combination will be = {a , a ,ab , ab , aab ...... ....... .. .. .. .. }
we are generating same combination again and again ! So if we simply backtrack to generate combination instead of using bit manipulation , we can overcome this problem .

* Please elaborate on how the same combinations are generated twice.
* Please elaborate on how backtrack resolves this problem _(repeating combinations)_.
* Please note down the time complexity. _(I think `O((3 power 9) lg (3 power 9))` per test case?)_
* If possible, use `scanf` explicitly instead of `scli, scli2 ..` macros. I strongly recommend to erase the `Case` macro and write the whole loop instead. Makes it convenient for the reader.

Let us know when you are done. :)

**Comment by rebornplusplus** [comment]
>  that `set-1[i][+set-2[j] == K` , and to do this we can do binary search

Oh also, here's a misplaced `[` and to make it less confusing, use `set_1, set_2` instead of `set-1, set-2` maybe.

**Comment by MahediKamal** [comment]
As this is my first contribution to this kind of work, I feel a little bit unsure.
I tried my best to make the changes you have suggested. 
It would be really kind of you if you could provide a review again.

**Comment by rebornplusplus** [comment]
Merged. 

Thank you for your good contribution. :100:

**Pull request merged**
